#
# ~/.bashrc
#

# If not running interactively, don't do anything
[[ $- != *i* ]] && return

# alias ls='ls --color=auto'
alias ls='eza --icons'
alias grep='grep --color=auto'
alias cls='clear'
alias claude='claude --dangerously-skip-permissions'

# The i3 keybindings, printed. The same script draws the searchable rofi list
# on $mod+F1 - it prints here because stdout is a terminal. `keys shot` filters.
alias keys='$HOME/.config/i3/script/shortcuts.sh'
PS1='[\u@\h \W]\$ '

# starship
# The prompt is generated from the wallpaper along with everything else, so
# point starship at the generated config rather than ~/.config/starship.toml.
# If the palette has never been generated, starship falls back to its default.
if [[ -f "$HOME/.cache/theme/starship.toml" ]]; then
    export STARSHIP_CONFIG="$HOME/.cache/theme/starship.toml"
fi
eval "$(starship init bash)"

# Make the current palette available to interactive shells and scripts
# ($THEME_ACCENT, $THEME_BASE, ...).
[[ -f "$HOME/.cache/theme/colors.sh" ]] && . "$HOME/.cache/theme/colors.sh"

# Put the line below in ~/.bashrc or ~/bash_profile:
#
#   eval "$(jump shell bash)"
#
# The following lines are autogenerated:

__jump_prompt_command() {
  local status=$?
  jump chdir && return $status
}

__jump_hint() {
  local term="${COMP_LINE/#j /}"
  echo \'$(jump hint "$term")\'
}

j() {
  local dir="$(jump cd "$@")"
  test -d "$dir"  && cd "$dir"
}

[[ "$PROMPT_COMMAND" =~ __jump_prompt_command ]] || {
  PROMPT_COMMAND="__jump_prompt_command;$PROMPT_COMMAND"
}

complete -o dirnames -C '__jump_hint' j
export PATH="$HOME/.local/bin:$PATH"
