#
# ~/.bashrc
#

# If not running interactively, don't do anything
[[ $- != *i* ]] && return

# alias ls='ls --color=auto'
alias ls='eza --icons=always'
alias grep='grep --color=auto'
alias cls='clear'
alias claude='claude --dangerously-skip-permissions'
alias reload='source ~/.bashrc'

# The i3 keybindings, printed. The same script draws the searchable rofi list
# on $mod+F1 - it prints here because stdout is a terminal. `keys shot` filters.
alias keys='$HOME/.config/i3/script/shortcuts.sh'
PS1='[\u@\h \W]\$ '

# starship
# The prompt is generated from the wallpaper along with everything else, so
# point starship at the generated config rather than ~/.config/starship.toml.
# If the palette has never been generated, starship falls back to its default.
if [[ -f "$HOME/.cache/theme/starship.toml" ]]; then
    export STARSHIP_CONFIG="$HOME/.cache/theme/starship.toml"
fi
eval "$(starship init bash)"

# Make the current palette available to interactive shells and scripts
# ($THEME_ACCENT, $THEME_BASE, ...).
[[ -f "$HOME/.cache/theme/colors.sh" ]] && . "$HOME/.cache/theme/colors.sh"

# Put the line below in ~/.bashrc or ~/bash_profile:
#
#   eval "$(jump shell bash)"
#
# The following lines are autogenerated:

__jump_prompt_command() {
  local status=$?
  jump chdir && return $status
}

__jump_hint() {
  local term="${COMP_LINE/#j /}"
  echo \'$(jump hint "$term")\'
}

j() {
  local dir="$(jump cd "$@")"
  test -d "$dir"  && cd "$dir"
}

[[ "$PROMPT_COMMAND" =~ __jump_prompt_command ]] || {
  PROMPT_COMMAND="__jump_prompt_command;$PROMPT_COMMAND"
}

complete -o dirnames -C '__jump_hint' j
export PATH="$HOME/.local/bin:$PATH"
export PATH="$HOME/develop/flutter/bin:$PATH"

# Android SDK (added by setup-android-sdk-arch.sh)
export ANDROID_HOME="/home/a8/Android/Sdk"
export ANDROID_SDK_ROOT="/home/a8/Android/Sdk"
export PATH="$ANDROID_HOME/platform-tools:$ANDROID_HOME/cmdline-tools/latest/bin:$PATH"

export PATH=/home/a8/bin:$PATH
export PATH=$PATH:$HOME/go/bin
export PATH=$PATH:/home/a8/Projects/boot.dev.workspace/worldbanc/private/bin

set -o vi

# Recolour .inputrc's vi-mode indicator from the generated palette, as a
# filled pill in the same style as starship's username segment
# (bg:accent fg:base) - so it reads as part of the same prompt rather than a
# bolted-on red/green label. Only runs once colors.sh has actually been
# sourced above; before the first wallpaper, .inputrc's plain ANSI fallback
# stands.
if [[ -n "${THEME_ACCENT:-}" ]]; then
    _hex_to_rgb() {
        local hex="${1#\#}"
        printf '%d;%d;%d' "0x${hex:0:2}" "0x${hex:2:2}" "0x${hex:4:2}"
    }
    _vi_fg="$(_hex_to_rgb "$THEME_BASE")"
    _vi_cmd_bg="$(_hex_to_rgb "$THEME_ACCENT")"
    _vi_ins_bg="$(_hex_to_rgb "$THEME_GREEN")"

    bind "set vi-cmd-mode-string $(printf '\001\e[1m\e[38;2;%sm\e[48;2;%sm\002 NORMAL \001\e[0m\002' "$_vi_fg" "$_vi_cmd_bg")"
    bind "set vi-ins-mode-string $(printf '\001\e[1m\e[38;2;%sm\e[48;2;%sm\002 INSERT \001\e[0m\002' "$_vi_fg" "$_vi_ins_bg")"

    unset -f _hex_to_rgb
    unset _vi_fg _vi_cmd_bg _vi_ins_bg
fi
