"""
Writers - one function per program that needs to be told about the palette.

Two output roots, and the split is not arbitrary:

  ~/.cache/theme/          for programs that can be pointed at an absolute
                           path (nvim via dofile, starship via STARSHIP_CONFIG,
                           shell scripts via source).

  ~/.config/<program>/     for programs whose include mechanism only reliably
                           resolves a file sitting next to their main config
                           (polybar, rofi, i3, kitty, dunst, gtk).

The second group is why postinstall stows with --no-folding: it makes
~/.config/kitty a real directory holding a symlinked kitty.conf, so a
generated current-theme.conf lands beside it instead of inside the git repo.
"""

import json
import os

HEADER = "generated by theme_engine - edits are overwritten on every wallpaper change"


def _write(path, content):
    os.makedirs(os.path.dirname(path), exist_ok=True)
    with open(path, "w") as f:
        f.write(content)
    return path


def _rgba(hex_color, alpha="ff"):
    return hex_color + alpha


# ============================================================================
# ~/.cache/theme/
# ============================================================================


def shell(p, path):
    """Plain shell variables. Sourced by the i3lock scripts and anything else."""
    lines = [f"# {HEADER}", ""]
    for k, v in sorted(p.items()):
        lines.append(f'THEME_{k.upper().replace("-", "_")}="{v}"')
    lines.append("")
    return _write(path, "\n".join(lines))


def json_dump(p, path):
    """The palette as data, for debugging and for anything added later."""
    return _write(path, json.dumps(p, indent=2, sort_keys=True) + "\n")


def nvim(p, path):
    """A complete small colorscheme, loaded with dofile().

    Deliberately not a plugin: it has to work on a fresh machine before
    lazy.nvim has ever run, and it has to be regenerated per wallpaper.
    Covers the groups that are actually visible in this setup - treesitter
    captures, LSP diagnostics, telescope, nvim-tree, lualine's backdrop.
    """
    g = [
        # --- editor chrome ---
        ("Normal", p["text"], p["base"]),
        ("NormalFloat", p["text"], p["mantle"]),
        ("FloatBorder", p["overlay0"], p["mantle"]),
        ("ColorColumn", None, p["surface0"]),
        ("Cursor", p["base"], p["cursor"]),
        ("CursorLine", None, p["surface0"]),
        ("CursorLineNr", p["accent"], None),
        ("LineNr", p["overlay0"], None),
        ("SignColumn", None, p["base"]),
        ("VertSplit", p["surface1"], None),
        ("WinSeparator", p["surface1"], None),
        ("Folded", p["subtext"], p["surface0"]),
        ("MatchParen", p["accent"], p["surface1"]),
        ("Visual", None, p["selection"]),
        ("Search", p["base"], p["yellow"]),
        ("IncSearch", p["base"], p["accent"]),
        ("Pmenu", p["subtext"], p["surface0"]),
        ("PmenuSel", p["base"], p["accent"]),
        ("PmenuSbar", None, p["surface1"]),
        ("PmenuThumb", None, p["overlay0"]),
        ("StatusLine", p["text"], p["surface0"]),
        ("StatusLineNC", p["muted"], p["mantle"]),
        ("TabLine", p["muted"], p["mantle"]),
        ("TabLineSel", p["base"], p["accent"]),
        ("TabLineFill", None, p["crust"]),
        ("Title", p["accent"], None),
        ("Directory", p["blue"], None),
        ("NonText", p["surface2"], None),
        ("Whitespace", p["surface1"], None),
        ("EndOfBuffer", p["base"], None),
        # --- syntax ---
        ("Comment", p["muted"], None),
        ("Constant", p["yellow"], None),
        ("String", p["green"], None),
        ("Character", p["green"], None),
        ("Number", p["yellow"], None),
        ("Boolean", p["yellow"], None),
        ("Float", p["yellow"], None),
        ("Identifier", p["text"], None),
        ("Function", p["blue"], None),
        ("Statement", p["magenta"], None),
        ("Conditional", p["magenta"], None),
        ("Repeat", p["magenta"], None),
        ("Label", p["magenta"], None),
        ("Operator", p["cyan"], None),
        ("Keyword", p["magenta"], None),
        ("Exception", p["red"], None),
        ("PreProc", p["cyan"], None),
        ("Include", p["magenta"], None),
        ("Define", p["magenta"], None),
        ("Macro", p["cyan"], None),
        ("Type", p["yellow"], None),
        ("StorageClass", p["yellow"], None),
        ("Structure", p["yellow"], None),
        ("Typedef", p["yellow"], None),
        ("Special", p["accent"], None),
        ("Delimiter", p["subtext"], None),
        ("Todo", p["base"], p["yellow"]),
        ("Error", p["red"], None),
        # --- diagnostics ---
        ("DiagnosticError", p["red"], None),
        ("DiagnosticWarn", p["yellow"], None),
        ("DiagnosticInfo", p["blue"], None),
        ("DiagnosticHint", p["cyan"], None),
        ("DiagnosticOk", p["green"], None),
        # --- diffs / git ---
        ("DiffAdd", p["green"], p["surface0"]),
        ("DiffChange", p["yellow"], p["surface0"]),
        ("DiffDelete", p["red"], p["surface0"]),
        ("DiffText", p["base"], p["blue"]),
        ("Added", p["green"], None),
        ("Changed", p["yellow"], None),
        ("Removed", p["red"], None),
        # --- treesitter ---
        ("@variable", p["text"], None),
        ("@variable.builtin", p["red"], None),
        ("@parameter", p["subtext"], None),
        ("@field", p["blue"], None),
        ("@property", p["blue"], None),
        ("@function", p["blue"], None),
        ("@function.builtin", p["cyan"], None),
        ("@method", p["blue"], None),
        ("@constructor", p["yellow"], None),
        ("@keyword", p["magenta"], None),
        ("@punctuation.bracket", p["overlay1"], None),
        ("@punctuation.delimiter", p["overlay1"], None),
        ("@tag", p["magenta"], None),
        ("@tag.attribute", p["yellow"], None),
        ("@tag.delimiter", p["overlay1"], None),
        ("@comment", p["muted"], None),
        # --- plugins in this config ---
        ("TelescopeNormal", p["subtext"], p["mantle"]),
        ("TelescopeBorder", p["mantle"], p["mantle"]),
        ("TelescopePromptNormal", p["text"], p["surface0"]),
        ("TelescopePromptBorder", p["surface0"], p["surface0"]),
        ("TelescopePromptTitle", p["base"], p["accent"]),
        ("TelescopePreviewTitle", p["base"], p["green"]),
        ("TelescopeResultsTitle", p["mantle"], p["mantle"]),
        ("TelescopeSelection", p["text"], p["surface1"]),
        ("TelescopeMatching", p["accent"], None),
        ("NvimTreeNormal", p["subtext"], p["mantle"]),
        ("NvimTreeRootFolder", p["accent"], None),
        ("NvimTreeFolderIcon", p["blue"], None),
        ("NvimTreeIndentMarker", p["surface1"], None),
        ("NvimTreeGitDirty", p["yellow"], None),
        ("NvimTreeGitNew", p["green"], None),
        ("NvimTreeGitDeleted", p["red"], None),
        ("NvimTreeSpecialFile", p["magenta"], None),
        ("NvimTreeWinSeparator", p["mantle"], p["mantle"]),
    ]

    out = [
        f"-- {HEADER}",
        "vim.opt.termguicolors = true",
        "vim.g.colors_name = 'wallpaper'",
        "local hi = function(group, spec) vim.api.nvim_set_hl(0, group, spec) end",
        "",
    ]
    for group, fg, bg in g:
        parts = []
        if fg:
            parts.append(f"fg='{fg}'")
        if bg:
            parts.append(f"bg='{bg}'")
        out.append(f"hi('{group}', {{{', '.join(parts)}}})")

    # Terminal colours inside :terminal, so a shell in nvim matches kitty.
    out.append("")
    ansi = [
        "black", "red", "green", "yellow", "blue", "magenta", "cyan", "white",
        "bright_black", "bright_red", "bright_green", "bright_yellow",
        "bright_blue", "bright_magenta", "bright_cyan", "bright_white",
    ]
    for i, name in enumerate(ansi):
        out.append(f"vim.g.terminal_color_{i} = '{p[name]}'")
    out.append("")
    return _write(path, "\n".join(out))


def starship(p, path):
    """Full starship config, generated so the prompt segments match the bar.

    The upstream config had a hardcoded pink/blue gradient that matched
    nothing; this keeps the same powerline shape but sources every colour
    from the palette.
    """
    # The powerline format block is a plain string: it contains starship's own
    # triple-quotes and a lot of backslashes, and escaping all that inside an
    # f-string is how you get a config that silently fails to parse.
    q = '"""'
    fmt = (
        f"format = {q}\n"
        "[](fg:accent)\\\n"
        "$username\\\n"
        "[](fg:accent bg:surface2)\\\n"
        "$directory\\\n"
        "[](fg:surface2 bg:surface1)\\\n"
        "$git_branch\\\n"
        "$git_status\\\n"
        "[](fg:surface1 bg:surface0)\\\n"
        "$c\\\n"
        "$golang\\\n"
        "$java\\\n"
        "$nodejs\\\n"
        "$python\\\n"
        "$rust\\\n"
        "$docker_context\\\n"
        "[](fg:surface0 bg:mantle)\\\n"
        "$time\\\n"
        "[ ](fg:mantle)\\\n"
        f"{q}\n"
    )

    content = f"# {HEADER}\n\n" + fmt

    content += f"""
palette = "wallpaper"

[palettes.wallpaper]
accent    = "{p['accent']}"
base      = "{p['base']}"
mantle    = "{p['mantle']}"
surface0  = "{p['surface0']}"
surface1  = "{p['surface1']}"
surface2  = "{p['surface2']}"
text      = "{p['text']}"
subtext   = "{p['subtext']}"
muted     = "{p['muted']}"
red       = "{p['red']}"
green     = "{p['green']}"
yellow    = "{p['yellow']}"
blue      = "{p['blue']}"

[username]
show_always = true
style_user = "bg:accent fg:base"
style_root = "bg:accent fg:base"
format = '[ $user ]($style)'
disabled = false

[directory]
style = "bg:surface2 fg:text"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = " "
"Pictures" = " "

[git_branch]
symbol = ""
style = "bg:surface1 fg:text"
format = '[ $symbol $branch ]($style)'

[git_status]
style = "bg:surface1 fg:yellow"
format = '[$all_status$ahead_behind ]($style)'

[c]
symbol = " "
style = "bg:surface0 fg:subtext"
format = '[ $symbol ($version) ]($style)'

[golang]
symbol = " "
style = "bg:surface0 fg:subtext"
format = '[ $symbol ($version) ]($style)'

[java]
symbol = " "
style = "bg:surface0 fg:subtext"
format = '[ $symbol ($version) ]($style)'

[nodejs]
symbol = ""
style = "bg:surface0 fg:subtext"
format = '[ $symbol ($version) ]($style)'

[python]
symbol = " "
style = "bg:surface0 fg:subtext"
format = '[ $symbol ($version) ]($style)'

[rust]
symbol = ""
style = "bg:surface0 fg:subtext"
format = '[ $symbol ($version) ]($style)'

[docker_context]
symbol = " "
style = "bg:surface0 fg:subtext"
format = '[ $symbol $context ]($style)'

[time]
disabled = false
time_format = "%R"
style = "bg:mantle fg:muted"
format = '[   $time ]($style)'

[character]
success_symbol = "[❯](bold green)"
error_symbol = "[❯](bold red)"
"""
    return _write(path, content)


# ============================================================================
# ~/.config/<program>/
# ============================================================================


def polybar(p, path):
    """[color] section included by shades/config.ini.

    Key names are frozen: bars.ini, modules.ini and user_modules.ini reference
    ${color.shade1..8}, ${color.foreground} and friends in ~100 places.
    """
    lines = [f"; {HEADER}", "", "[color]", "; main"]
    for k in ("background", "foreground", "foreground-alt"):
        lines.append(f"{k} = {p[k]}")
    lines += ["", "; shades (surface ramp, tipping into the accent at the top)"]
    for i in range(1, 9):
        lines.append(f"shade{i} = {p[f'shade{i}']}")
    lines += ["", "; semantic - prefer these in new modules"]
    for k in ("base", "mantle", "crust", "surface0", "surface1", "surface2",
              "overlay0", "overlay1", "text", "subtext", "muted", "accent",
              "accent_dim", "urgent", "warning", "success", "info",
              "red", "green", "yellow", "blue", "magenta", "cyan"):
        lines.append(f"{k} = {p[k]}")
    lines.append("")
    return _write(path, "\n".join(lines))


def rofi(p, path):
    """Colour variables imported by ~/.config/rofi/theme.rasi."""
    content = f"""/* {HEADER} */

* {{
    al:       #00000000;
    bg:       {_rgba(p['base'])};
    bg-alt:   {_rgba(p['mantle'])};
    bg-sel:   {_rgba(p['surface1'])};
    bg-bar:   {_rgba(p['surface0'])};
    fg:       {_rgba(p['text'])};
    fg-alt:   {_rgba(p['muted'])};
    accent:   {_rgba(p['accent'])};
    urgent:   {_rgba(p['urgent'])};
    border:   {_rgba(p['surface2'])};

    /* the older names, kept so any stray .rasi still resolves */
    bg1:      {_rgba(p['surface0'])};
    bg2:      {_rgba(p['surface1'])};
    bg3:      {_rgba(p['surface2'])};
    bg4:      {_rgba(p['overlay0'])};
}}
"""
    return _write(path, content)


def i3(p, path):
    """client.* colours plus $variables, included from ~/.config/i3/config."""
    content = f"""# {HEADER}

set $base       {p['base']}
set $mantle     {p['mantle']}
set $crust      {p['crust']}
set $surface0   {p['surface0']}
set $surface1   {p['surface1']}
set $surface2   {p['surface2']}
set $overlay0   {p['overlay0']}
set $text       {p['text']}
set $subtext    {p['subtext']}
set $muted      {p['muted']}
set $accent     {p['accent']}
set $accent_dim {p['accent_dim']}
set $urgent     {p['urgent']}

# class                 border      background  text     indicator    child_border
client.focused          $accent     $surface0   $text    $accent      $accent
client.focused_inactive $surface1   $mantle     $subtext $surface1    $surface1
client.unfocused        $surface0   $base       $muted   $surface0    $surface0
client.urgent           $urgent     $urgent     $base    $urgent      $urgent
client.placeholder      $surface0   $base       $muted   $surface0    $surface0
client.background       $base
"""
    return _write(path, content)


def kitty(p, path):
    """~/.config/kitty/current-theme.conf - kitty.conf already includes it."""
    content = f"""# {HEADER}

foreground              {p['text']}
background              {p['base']}
selection_foreground    {p['base']}
selection_background    {p['accent']}

cursor                  {p['cursor']}
cursor_text_color       {p['base']}
url_color               {p['accent']}

active_border_color     {p['accent']}
inactive_border_color   {p['surface1']}
bell_border_color       {p['warning']}

wayland_titlebar_color  system
macos_titlebar_color    system

active_tab_foreground   {p['base']}
active_tab_background   {p['accent']}
inactive_tab_foreground {p['subtext']}
inactive_tab_background {p['mantle']}
tab_bar_background      {p['crust']}

mark1_foreground {p['base']}
mark1_background {p['accent']}
mark2_foreground {p['base']}
mark2_background {p['magenta']}
mark3_foreground {p['base']}
mark3_background {p['cyan']}

# black
color0  {p['black']}
color8  {p['bright_black']}
# red
color1  {p['red']}
color9  {p['bright_red']}
# green
color2  {p['green']}
color10 {p['bright_green']}
# yellow
color3  {p['yellow']}
color11 {p['bright_yellow']}
# blue
color4  {p['blue']}
color12 {p['bright_blue']}
# magenta
color5  {p['magenta']}
color13 {p['bright_magenta']}
# cyan
color6  {p['cyan']}
color14 {p['bright_cyan']}
# white
color7  {p['white']}
color15 {p['bright_white']}
"""
    return _write(path, content)


def dunst(p, path):
    """A dunstrc.d drop-in. dunst reads ~/.config/dunst/dunstrc.d/*.conf after
    the main dunstrc, so this only has to carry colours."""
    content = f"""# {HEADER}

[urgency_low]
    background = "{p['mantle']}"
    foreground = "{p['muted']}"
    frame_color = "{p['surface1']}"
    timeout = 5

[urgency_normal]
    background = "{p['base']}"
    foreground = "{p['text']}"
    frame_color = "{p['accent']}"
    timeout = 8

[urgency_critical]
    background = "{p['base']}"
    foreground = "{p['text']}"
    frame_color = "{p['urgent']}"
    timeout = 0
"""
    return _write(path, content)


def gtk(p, path):
    """gtk.css for GTK3 and GTK4.

    Adwaita-dark does the widget drawing; this repaints the parts of it that
    would otherwise stay stock blue, so Thunar and pavucontrol sit in the same
    scheme as everything else.
    """
    content = f"""/* {HEADER} */

@define-color accent_color {p['accent']};
@define-color accent_bg_color {p['accent']};
@define-color accent_fg_color {p['base']};

@define-color theme_bg_color {p['base']};
@define-color theme_base_color {p['mantle']};
@define-color theme_fg_color {p['text']};
@define-color theme_text_color {p['text']};

@define-color theme_selected_bg_color {p['accent']};
@define-color theme_selected_fg_color {p['base']};

@define-color insensitive_fg_color {p['muted']};
@define-color insensitive_bg_color {p['surface0']};

@define-color borders {p['surface2']};
@define-color unfocused_borders {p['surface1']};

@define-color headerbar_bg_color {p['mantle']};
@define-color headerbar_fg_color {p['text']};
@define-color headerbar_border_color {p['surface1']};

@define-color popover_bg_color {p['mantle']};
@define-color popover_fg_color {p['text']};

@define-color view_bg_color {p['base']};
@define-color view_fg_color {p['text']};

@define-color window_bg_color {p['base']};
@define-color window_fg_color {p['text']};

@define-color card_bg_color {p['surface0']};
@define-color card_fg_color {p['text']};

@define-color sidebar_bg_color {p['mantle']};
@define-color sidebar_fg_color {p['subtext']};

@define-color error_color {p['red']};
@define-color warning_color {p['yellow']};
@define-color success_color {p['green']};
"""
    return _write(path, content)


def xresources(p, path):
    """*.color0..15 for the X resource database.

    Anything old-school that reads xrdb - i3lock, xterm, the odd Java app -
    picks the palette up from here.
    """
    ansi = [
        "black", "red", "green", "yellow", "blue", "magenta", "cyan", "white",
        "bright_black", "bright_red", "bright_green", "bright_yellow",
        "bright_blue", "bright_magenta", "bright_cyan", "bright_white",
    ]
    lines = [f"! {HEADER}", ""]
    lines.append(f"*.background: {p['base']}")
    lines.append(f"*.foreground: {p['text']}")
    lines.append(f"*.cursorColor: {p['cursor']}")
    lines.append("")
    for i, name in enumerate(ansi):
        lines.append(f"*.color{i}: {p[name]}")
    lines.append("")
    return _write(path, "\n".join(lines))
