"""
Writers - one function per program that needs to be told about the palette.

Output roots, and the split is not arbitrary:

  ~/.cache/theme/          for programs that can be pointed at an absolute
                           path (nvim via dofile, starship via STARSHIP_CONFIG,
                           shell scripts via source).

  ~/.config/<program>/     for programs whose include mechanism only reliably
                           resolves a file sitting next to their main config
                           (polybar, rofi, i3, kitty, dunst, gtk).

  ~/                       for programs that predate ~/.config and still only
                           look in $HOME (GTK2's ~/.gtkrc-2.0).

  ~/.mozilla/firefox/<p>/   Firefox, which keeps its whole configuration inside
                           each profile directory.

The second group is why postinstall stows with --no-folding: it makes
~/.config/kitty a real directory holding a symlinked kitty.conf, so a
generated current-theme.conf lands beside it instead of inside the git repo.
"""

import json
import os

HEADER = "generated by theme_engine - edits are overwritten on every wallpaper change"


def _write(path, content):
    os.makedirs(os.path.dirname(path), exist_ok=True)
    with open(path, "w") as f:
        f.write(content)
    return path


def _rgba(hex_color, alpha="ff"):
    return hex_color + alpha


# ============================================================================
# ~/.cache/theme/
# ============================================================================


def shell(p, path):
    """Plain shell variables. Sourced by the i3lock scripts and anything else."""
    lines = [f"# {HEADER}", ""]
    for k, v in sorted(p.items()):
        lines.append(f'THEME_{k.upper().replace("-", "_")}="{v}"')
    lines.append("")
    return _write(path, "\n".join(lines))


def json_dump(p, path):
    """The palette as data, for debugging and for anything added later."""
    return _write(path, json.dumps(p, indent=2, sort_keys=True) + "\n")


def nvim(p, path):
    """A complete small colorscheme, loaded with dofile().

    Deliberately not a plugin: it has to work on a fresh machine before
    lazy.nvim has ever run, and it has to be regenerated per wallpaper.
    Covers the groups that are actually visible in this setup - treesitter
    captures, LSP diagnostics, telescope, nvim-tree, lualine's backdrop.
    """
    g = [
        # --- editor chrome ---
        ("Normal", p["text"], p["base"]),
        ("NormalFloat", p["text"], p["mantle"]),
        ("FloatBorder", p["overlay0"], p["mantle"]),
        ("ColorColumn", None, p["surface0"]),
        ("Cursor", p["base"], p["cursor"]),
        ("CursorLine", None, p["surface0"]),
        ("CursorLineNr", p["accent"], None),
        ("LineNr", p["overlay0"], None),
        ("SignColumn", None, p["base"]),
        ("VertSplit", p["surface1"], None),
        ("WinSeparator", p["surface1"], None),
        ("Folded", p["subtext"], p["surface0"]),
        ("MatchParen", p["accent"], p["surface1"]),
        ("Visual", None, p["selection"]),
        ("Search", p["base"], p["yellow"]),
        ("IncSearch", p["base"], p["accent"]),
        ("Pmenu", p["subtext"], p["surface0"]),
        ("PmenuSel", p["base"], p["accent"]),
        ("PmenuSbar", None, p["surface1"]),
        ("PmenuThumb", None, p["overlay0"]),
        ("StatusLine", p["text"], p["surface0"]),
        ("StatusLineNC", p["muted"], p["mantle"]),
        ("TabLine", p["muted"], p["mantle"]),
        ("TabLineSel", p["base"], p["accent"]),
        ("TabLineFill", None, p["crust"]),
        ("Title", p["accent"], None),
        ("Directory", p["blue"], None),
        ("NonText", p["surface2"], None),
        ("Whitespace", p["surface1"], None),
        ("EndOfBuffer", p["base"], None),
        # --- syntax ---
        ("Comment", p["muted"], None),
        ("Constant", p["yellow"], None),
        ("String", p["green"], None),
        ("Character", p["green"], None),
        ("Number", p["yellow"], None),
        ("Boolean", p["yellow"], None),
        ("Float", p["yellow"], None),
        ("Identifier", p["text"], None),
        ("Function", p["blue"], None),
        ("Statement", p["magenta"], None),
        ("Conditional", p["magenta"], None),
        ("Repeat", p["magenta"], None),
        ("Label", p["magenta"], None),
        ("Operator", p["cyan"], None),
        ("Keyword", p["magenta"], None),
        ("Exception", p["red"], None),
        ("PreProc", p["cyan"], None),
        ("Include", p["magenta"], None),
        ("Define", p["magenta"], None),
        ("Macro", p["cyan"], None),
        ("Type", p["yellow"], None),
        ("StorageClass", p["yellow"], None),
        ("Structure", p["yellow"], None),
        ("Typedef", p["yellow"], None),
        ("Special", p["accent"], None),
        ("Delimiter", p["subtext"], None),
        ("Todo", p["base"], p["yellow"]),
        ("Error", p["red"], None),
        # --- diagnostics ---
        ("DiagnosticError", p["red"], None),
        ("DiagnosticWarn", p["yellow"], None),
        ("DiagnosticInfo", p["blue"], None),
        ("DiagnosticHint", p["cyan"], None),
        ("DiagnosticOk", p["green"], None),
        # --- diffs / git ---
        ("DiffAdd", p["green"], p["surface0"]),
        ("DiffChange", p["yellow"], p["surface0"]),
        ("DiffDelete", p["red"], p["surface0"]),
        ("DiffText", p["base"], p["blue"]),
        ("Added", p["green"], None),
        ("Changed", p["yellow"], None),
        ("Removed", p["red"], None),
        # --- treesitter ---
        ("@variable", p["text"], None),
        ("@variable.builtin", p["red"], None),
        ("@parameter", p["subtext"], None),
        ("@field", p["blue"], None),
        ("@property", p["blue"], None),
        ("@function", p["blue"], None),
        ("@function.builtin", p["cyan"], None),
        ("@method", p["blue"], None),
        ("@constructor", p["yellow"], None),
        ("@keyword", p["magenta"], None),
        ("@punctuation.bracket", p["overlay1"], None),
        ("@punctuation.delimiter", p["overlay1"], None),
        ("@tag", p["magenta"], None),
        ("@tag.attribute", p["yellow"], None),
        ("@tag.delimiter", p["overlay1"], None),
        ("@comment", p["muted"], None),
        # --- plugins in this config ---
        ("TelescopeNormal", p["subtext"], p["mantle"]),
        ("TelescopeBorder", p["mantle"], p["mantle"]),
        ("TelescopePromptNormal", p["text"], p["surface0"]),
        ("TelescopePromptBorder", p["surface0"], p["surface0"]),
        ("TelescopePromptTitle", p["base"], p["accent"]),
        ("TelescopePreviewTitle", p["base"], p["green"]),
        ("TelescopeResultsTitle", p["mantle"], p["mantle"]),
        ("TelescopeSelection", p["text"], p["surface1"]),
        ("TelescopeMatching", p["accent"], None),
        ("NvimTreeNormal", p["subtext"], p["mantle"]),
        ("NvimTreeRootFolder", p["accent"], None),
        ("NvimTreeFolderIcon", p["blue"], None),
        ("NvimTreeIndentMarker", p["surface1"], None),
        ("NvimTreeGitDirty", p["yellow"], None),
        ("NvimTreeGitNew", p["green"], None),
        ("NvimTreeGitDeleted", p["red"], None),
        ("NvimTreeSpecialFile", p["magenta"], None),
        ("NvimTreeWinSeparator", p["mantle"], p["mantle"]),
    ]

    out = [
        f"-- {HEADER}",
        "vim.opt.termguicolors = true",
        "vim.g.colors_name = 'wallpaper'",
        "local hi = function(group, spec) vim.api.nvim_set_hl(0, group, spec) end",
        "",
    ]
    for group, fg, bg in g:
        parts = []
        if fg:
            parts.append(f"fg='{fg}'")
        if bg:
            parts.append(f"bg='{bg}'")
        out.append(f"hi('{group}', {{{', '.join(parts)}}})")

    # Terminal colours inside :terminal, so a shell in nvim matches kitty.
    out.append("")
    ansi = [
        "black", "red", "green", "yellow", "blue", "magenta", "cyan", "white",
        "bright_black", "bright_red", "bright_green", "bright_yellow",
        "bright_blue", "bright_magenta", "bright_cyan", "bright_white",
    ]
    for i, name in enumerate(ansi):
        out.append(f"vim.g.terminal_color_{i} = '{p[name]}'")
    out.append("")
    return _write(path, "\n".join(out))


def starship(p, path):
    """Full starship config, generated so the prompt segments match the bar.

    The upstream config had a hardcoded pink/blue gradient that matched
    nothing; this keeps the same powerline shape but sources every colour
    from the palette.
    """
    # The powerline format block is a plain string: it contains starship's own
    # triple-quotes and a lot of backslashes, and escaping all that inside an
    # f-string is how you get a config that silently fails to parse.
    q = '"""'
    fmt = (
        f"format = {q}\n"
        "[](fg:accent)\\\n"
        "$username\\\n"
        "[](fg:accent bg:surface2)\\\n"
        "$directory\\\n"
        "[](fg:surface2 bg:surface1)\\\n"
        "$git_branch\\\n"
        "$git_status\\\n"
        "[](fg:surface1 bg:surface0)\\\n"
        "$c\\\n"
        "$golang\\\n"
        "$java\\\n"
        "$nodejs\\\n"
        "$python\\\n"
        "$rust\\\n"
        "$docker_context\\\n"
        "[](fg:surface0 bg:mantle)\\\n"
        "$time\\\n"
        "[ ](fg:mantle)\\\n"
        f"{q}\n"
    )

    content = f"# {HEADER}\n\n" + fmt

    content += f"""
palette = "wallpaper"

[palettes.wallpaper]
accent    = "{p['accent']}"
base      = "{p['base']}"
mantle    = "{p['mantle']}"
surface0  = "{p['surface0']}"
surface1  = "{p['surface1']}"
surface2  = "{p['surface2']}"
text      = "{p['text']}"
subtext   = "{p['subtext']}"
muted     = "{p['muted']}"
red       = "{p['red']}"
green     = "{p['green']}"
yellow    = "{p['yellow']}"
blue      = "{p['blue']}"

[username]
show_always = true
style_user = "bg:accent fg:base"
style_root = "bg:accent fg:base"
format = '[ $user ]($style)'
disabled = false

[directory]
style = "bg:surface2 fg:text"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = " "
"Pictures" = " "

[git_branch]
symbol = ""
style = "bg:surface1 fg:text"
format = '[ $symbol $branch ]($style)'

[git_status]
style = "bg:surface1 fg:yellow"
format = '[$all_status$ahead_behind ]($style)'

[c]
symbol = " "
style = "bg:surface0 fg:subtext"
format = '[ $symbol ($version) ]($style)'

[golang]
symbol = " "
style = "bg:surface0 fg:subtext"
format = '[ $symbol ($version) ]($style)'

[java]
symbol = " "
style = "bg:surface0 fg:subtext"
format = '[ $symbol ($version) ]($style)'

[nodejs]
symbol = ""
style = "bg:surface0 fg:subtext"
format = '[ $symbol ($version) ]($style)'

[python]
symbol = " "
style = "bg:surface0 fg:subtext"
format = '[ $symbol ($version) ]($style)'

[rust]
symbol = ""
style = "bg:surface0 fg:subtext"
format = '[ $symbol ($version) ]($style)'

[docker_context]
symbol = " "
style = "bg:surface0 fg:subtext"
format = '[ $symbol $context ]($style)'

[time]
disabled = false
time_format = "%R"
style = "bg:mantle fg:muted"
format = '[   $time ]($style)'

[character]
success_symbol = "[❯](bold green)"
error_symbol = "[❯](bold red)"
"""
    return _write(path, content)


# ============================================================================
# ~/.config/<program>/
# ============================================================================


def polybar(p, path):
    """[color] section included by shades/config.ini.

    Key names are frozen: bars.ini, modules.ini and user_modules.ini reference
    ${color.shade1..8}, ${color.foreground} and friends in ~100 places.
    """
    lines = [f"; {HEADER}", "", "[color]", "; main"]
    for k in ("background", "foreground", "foreground-alt"):
        lines.append(f"{k} = {p[k]}")
    lines += ["", "; shades (surface ramp, tipping into the accent at the top)"]
    for i in range(1, 9):
        lines.append(f"shade{i} = {p[f'shade{i}']}")
    lines += ["", "; semantic - prefer these in new modules"]
    for k in ("base", "mantle", "crust", "surface0", "surface1", "surface2",
              "overlay0", "overlay1", "text", "subtext", "muted", "accent",
              "accent_dim", "urgent", "warning", "success", "info",
              "red", "green", "yellow", "blue", "magenta", "cyan"):
        lines.append(f"{k} = {p[k]}")
    lines.append("")
    return _write(path, "\n".join(lines))


def rofi(p, path):
    """Colour variables imported by ~/.config/rofi/theme.rasi."""
    content = f"""/* {HEADER} */

* {{
    al:       #00000000;
    bg:       {_rgba(p['base'])};
    bg-alt:   {_rgba(p['mantle'])};
    bg-sel:   {_rgba(p['surface1'])};
    bg-bar:   {_rgba(p['surface0'])};
    fg:       {_rgba(p['text'])};
    fg-alt:   {_rgba(p['muted'])};
    accent:   {_rgba(p['accent'])};
    urgent:   {_rgba(p['urgent'])};
    border:   {_rgba(p['surface2'])};

    /* the older names, kept so any stray .rasi still resolves */
    bg1:      {_rgba(p['surface0'])};
    bg2:      {_rgba(p['surface1'])};
    bg3:      {_rgba(p['surface2'])};
    bg4:      {_rgba(p['overlay0'])};
}}
"""
    return _write(path, content)


def i3(p, path):
    """client.* colours plus $variables, included from ~/.config/i3/config."""
    content = f"""# {HEADER}

set $base       {p['base']}
set $mantle     {p['mantle']}
set $crust      {p['crust']}
set $surface0   {p['surface0']}
set $surface1   {p['surface1']}
set $surface2   {p['surface2']}
set $overlay0   {p['overlay0']}
set $text       {p['text']}
set $subtext    {p['subtext']}
set $muted      {p['muted']}
set $accent     {p['accent']}
set $accent_dim {p['accent_dim']}
set $urgent     {p['urgent']}

# class                 border      background  text     indicator    child_border
client.focused          $accent     $surface0   $text    $accent      $accent
client.focused_inactive $surface1   $mantle     $subtext $surface1    $surface1
client.unfocused        $surface0   $base       $muted   $surface0    $surface0
client.urgent           $urgent     $urgent     $base    $urgent      $urgent
client.placeholder      $surface0   $base       $muted   $surface0    $surface0
client.background       $base
"""
    return _write(path, content)


def kitty(p, path):
    """~/.config/kitty/current-theme.conf - kitty.conf already includes it."""
    content = f"""# {HEADER}

foreground              {p['text']}
background              {p['base']}
selection_foreground    {p['base']}
selection_background    {p['accent']}

cursor                  {p['cursor']}
cursor_text_color       {p['base']}
url_color               {p['accent']}

active_border_color     {p['accent']}
inactive_border_color   {p['surface1']}
bell_border_color       {p['warning']}

wayland_titlebar_color  system
macos_titlebar_color    system

active_tab_foreground   {p['base']}
active_tab_background   {p['accent']}
inactive_tab_foreground {p['subtext']}
inactive_tab_background {p['mantle']}
tab_bar_background      {p['crust']}

mark1_foreground {p['base']}
mark1_background {p['accent']}
mark2_foreground {p['base']}
mark2_background {p['magenta']}
mark3_foreground {p['base']}
mark3_background {p['cyan']}

# black
color0  {p['black']}
color8  {p['bright_black']}
# red
color1  {p['red']}
color9  {p['bright_red']}
# green
color2  {p['green']}
color10 {p['bright_green']}
# yellow
color3  {p['yellow']}
color11 {p['bright_yellow']}
# blue
color4  {p['blue']}
color12 {p['bright_blue']}
# magenta
color5  {p['magenta']}
color13 {p['bright_magenta']}
# cyan
color6  {p['cyan']}
color14 {p['bright_cyan']}
# white
color7  {p['white']}
color15 {p['bright_white']}
"""
    return _write(path, content)


def dunst(p, path):
    """A dunstrc.d drop-in. dunst reads ~/.config/dunst/dunstrc.d/*.conf after
    the main dunstrc, so this only has to carry colours."""
    content = f"""# {HEADER}

[urgency_low]
    background = "{p['mantle']}"
    foreground = "{p['muted']}"
    frame_color = "{p['surface1']}"
    timeout = 5

[urgency_normal]
    background = "{p['base']}"
    foreground = "{p['text']}"
    frame_color = "{p['accent']}"
    timeout = 8

[urgency_critical]
    background = "{p['base']}"
    foreground = "{p['text']}"
    frame_color = "{p['urgent']}"
    timeout = 0
"""
    return _write(path, content)


def gtk(p, path):
    """gtk.css for GTK3 and GTK4.

    Adwaita-dark does the widget drawing; this repaints the parts of it that
    would otherwise stay stock blue, so Thunar and pavucontrol sit in the same
    scheme as everything else.

    Two halves. The @define-color block is the important one: Adwaita's own
    stylesheet is written in terms of these names, so redefining them recolours
    every widget it draws. The rules after it are for the places where Adwaita
    hardcodes a colour instead of naming one - Thunar's sidebar and location
    bar are the ones that show up immediately.
    """
    content = f"""/* {HEADER} */

/* ---- named colours ------------------------------------------------------
 * Adwaita (GTK3) and libadwaita (GTK4) both look these up by name, so
 * redefining them here repaints the stock theme rather than replacing it.
 */

@define-color accent_color {p['accent']};
@define-color accent_bg_color {p['accent']};
@define-color accent_fg_color {p['base']};

@define-color theme_bg_color {p['base']};
@define-color theme_base_color {p['mantle']};
@define-color theme_fg_color {p['text']};
@define-color theme_text_color {p['text']};

@define-color theme_selected_bg_color {p['accent']};
@define-color theme_selected_fg_color {p['base']};

/* GTK2-era aliases. Plenty of GTK3 themes and apps still reference these. */
@define-color selected_bg_color {p['accent']};
@define-color selected_fg_color {p['base']};
@define-color bg_color {p['base']};
@define-color fg_color {p['text']};
@define-color base_color {p['mantle']};
@define-color text_color {p['text']};

@define-color insensitive_fg_color {p['muted']};
@define-color insensitive_bg_color {p['surface0']};
@define-color insensitive_base_color {p['mantle']};

@define-color theme_unfocused_bg_color {p['base']};
@define-color theme_unfocused_base_color {p['mantle']};
@define-color theme_unfocused_fg_color {p['subtext']};
@define-color theme_unfocused_text_color {p['subtext']};
@define-color theme_unfocused_selected_bg_color {p['surface2']};
@define-color theme_unfocused_selected_fg_color {p['text']};

@define-color borders {p['surface2']};
@define-color unfocused_borders {p['surface1']};

@define-color headerbar_bg_color {p['mantle']};
@define-color headerbar_fg_color {p['text']};
@define-color headerbar_border_color {p['surface1']};
@define-color headerbar_backdrop_color {p['crust']};
@define-color headerbar_shade_color {p['crust']};

@define-color popover_bg_color {p['mantle']};
@define-color popover_fg_color {p['text']};

@define-color view_bg_color {p['base']};
@define-color view_fg_color {p['text']};

@define-color window_bg_color {p['base']};
@define-color window_fg_color {p['text']};

@define-color card_bg_color {p['surface0']};
@define-color card_fg_color {p['text']};

@define-color dialog_bg_color {p['mantle']};
@define-color dialog_fg_color {p['text']};

@define-color sidebar_bg_color {p['mantle']};
@define-color sidebar_fg_color {p['subtext']};
@define-color sidebar_backdrop_color {p['crust']};
@define-color sidebar_border_color {p['surface1']};
@define-color sidebar_shade_color {p['crust']};

@define-color error_color {p['red']};
@define-color error_bg_color {p['red']};
@define-color error_fg_color {p['base']};
@define-color warning_color {p['yellow']};
@define-color warning_bg_color {p['yellow']};
@define-color warning_fg_color {p['base']};
@define-color success_color {p['green']};
@define-color success_bg_color {p['green']};
@define-color success_fg_color {p['base']};
@define-color destructive_color {p['red']};
@define-color destructive_bg_color {p['red']};
@define-color destructive_fg_color {p['base']};

@define-color link_color {p['blue']};
@define-color visited_link_color {p['magenta']};

@define-color tooltip_bg_color {p['surface0']};
@define-color tooltip_fg_color {p['text']};

@define-color scrollbar_bg_color {p['mantle']};
@define-color scrollbar_slider_color {p['overlay0']};

/* ---- the places a named colour does not reach --------------------------- */

*:selected,
*:selected:focus {{
    background-color: {p['accent']};
    color: {p['base']};
}}

/* Thunar: the shortcuts sidebar, the path bar and the file list. Adwaita
 * paints these from its own greys, so they are the parts that stay stock
 * without this. */
.sidebar,
.sidebar list,
placessidebar,
placessidebar list {{
    background-color: {p['mantle']};
    color: {p['subtext']};
}}

placessidebar row:selected,
.sidebar row:selected {{
    background-color: {p['surface1']};
    color: {p['text']};
}}

.path-bar button,
.linked > button {{
    background-image: none;
    background-color: {p['surface0']};
    color: {p['text']};
    border-color: {p['surface1']};
}}

.path-bar button:checked,
.path-bar button:active {{
    background-color: {p['accent']};
    color: {p['base']};
}}

treeview.view {{
    background-color: {p['base']};
    color: {p['text']};
}}

treeview.view:selected {{
    background-color: {p['accent']};
    color: {p['base']};
}}

treeview.view header button {{
    background-image: none;
    background-color: {p['mantle']};
    color: {p['subtext']};
    border-color: {p['surface1']};
}}

entry, spinbutton {{
    background-color: {p['surface0']};
    color: {p['text']};
    border-color: {p['surface1']};
}}

entry:focus {{
    border-color: {p['accent']};
}}

entry selection {{
    background-color: {p['accent']};
    color: {p['base']};
}}

notebook > header {{
    background-color: {p['mantle']};
}}

notebook > header tab:checked {{
    box-shadow: inset 0 -3px {p['accent']};
    color: {p['text']};
}}

progressbar progress,
levelbar block.filled,
scale highlight {{
    background-color: {p['accent']};
}}

scrollbar {{
    background-color: {p['mantle']};
    border-color: {p['surface1']};
}}

scrollbar slider {{
    background-color: {p['overlay0']};
}}

scrollbar slider:hover {{
    background-color: {p['overlay1']};
}}

tooltip, tooltip.background {{
    background-color: {p['surface0']};
    color: {p['text']};
}}

menu, .menu, popover, popover contents {{
    background-color: {p['mantle']};
    color: {p['text']};
}}

menu menuitem:hover,
popover listview row:hover {{
    background-color: {p['surface1']};
    color: {p['text']};
}}

check:checked, radio:checked,
switch:checked {{
    background-color: {p['accent']};
    color: {p['base']};
}}
"""
    return _write(path, content)


def gtk2(p, path):
    """~/.gtkrc-2.0 - GTK2 is dead upstream and alive on any Arch desktop.

    Written unconditionally because it is one small file and the apps that
    need it (older GIMP, wicd-style tools, a few Wine dialogs) do not
    advertise themselves with a directory under ~/.config the way GTK3 does.
    GTK2 has no cascade: one style, applied to GtkWidget, is the whole theme.
    """
    content = f"""# {HEADER}

gtk-theme-name="Adwaita-dark"
gtk-icon-theme-name="Papirus-Dark"
gtk-cursor-theme-name="Adwaita"
gtk-cursor-theme-size=24
gtk-font-name="Fantasque Sans Mono 11"
gtk-enable-animations=1
gtk-xft-antialias=1
gtk-xft-hinting=1
gtk-xft-hintstyle="hintfull"
gtk-xft-rgba="rgb"

style "wallpaper" {{
    fg[NORMAL]        = "{p['text']}"
    fg[PRELIGHT]      = "{p['text']}"
    fg[ACTIVE]        = "{p['text']}"
    fg[SELECTED]      = "{p['base']}"
    fg[INSENSITIVE]   = "{p['muted']}"

    bg[NORMAL]        = "{p['base']}"
    bg[PRELIGHT]      = "{p['surface1']}"
    bg[ACTIVE]        = "{p['surface0']}"
    bg[SELECTED]      = "{p['accent']}"
    bg[INSENSITIVE]   = "{p['mantle']}"

    base[NORMAL]      = "{p['mantle']}"
    base[PRELIGHT]    = "{p['surface0']}"
    base[ACTIVE]      = "{p['surface1']}"
    base[SELECTED]    = "{p['accent']}"
    base[INSENSITIVE] = "{p['mantle']}"

    text[NORMAL]      = "{p['text']}"
    text[PRELIGHT]    = "{p['text']}"
    text[ACTIVE]      = "{p['text']}"
    text[SELECTED]    = "{p['base']}"
    text[INSENSITIVE] = "{p['muted']}"
}}

class "GtkWidget" style "wallpaper"
"""
    return _write(path, content)


# qt5ct/qt6ct store a QPalette as one comma-separated line per colour group,
# in QPalette::ColorRole enum order. The order is not documented anywhere in
# qt5ct - it is the enum - so it is spelled out here.
_QT_ROLES = (
    "WindowText", "Button", "Light", "Midlight", "Dark", "Mid", "Text",
    "BrightText", "ButtonText", "Base", "Window", "Shadow", "Highlight",
    "HighlightedText", "Link", "LinkVisited", "AlternateBase", "NoRole",
    "ToolTipBase", "ToolTipText", "PlaceholderText",
)


def _qt_group(p, disabled=False):
    """One qt5ct colour line: the 21 QPalette roles, in enum order."""
    fg = p["muted"] if disabled else p["text"]
    roles = {
        "WindowText": fg,
        "Button": p["surface0"],
        "Light": p["surface2"],
        "Midlight": p["surface1"],
        "Dark": p["crust"],
        "Mid": p["overlay0"],
        "Text": fg,
        "BrightText": p["accent"],
        "ButtonText": fg,
        "Base": p["mantle"],
        "Window": p["base"],
        "Shadow": p["crust"],
        "Highlight": p["surface1"] if disabled else p["accent"],
        "HighlightedText": p["muted"] if disabled else p["base"],
        "Link": p["blue"],
        "LinkVisited": p["magenta"],
        "AlternateBase": p["surface0"],
        "NoRole": p["base"],
        "ToolTipBase": p["surface0"],
        "ToolTipText": p["text"],
        "PlaceholderText": p["muted"],
    }
    return ", ".join(roles[r] for r in _QT_ROLES)


def qt_colors(p, path):
    """A qt5ct/qt6ct colour scheme - the palette Qt apps actually draw with."""
    active = _qt_group(p)
    content = f"""# {HEADER}

[ColorScheme]
active_colors={active}
inactive_colors={active}
disabled_colors={_qt_group(p, disabled=True)}
"""
    return _write(path, content)


def qtct(p, path):
    """qt5ct.conf / qt6ct.conf, generated whole.

    qt5ct only applies a custom palette when it is pointed at a scheme file by
    absolute path, so the conf has to be generated alongside the scheme rather
    than shipped as a static dotfile. Fusion is the style because it is the one
    Qt style that honours the palette for every widget; Breeze and the platform
    styles paint parts of themselves regardless.

    The [Fonts] section is deliberately absent - qt5ct stores fonts as
    QVariant-encoded binary, which is not something to hand-write, and leaving
    it out just means Qt keeps its own font settings.
    """
    # abspath, not just join: qt5ct resolves color_scheme_path relative to its
    # own working directory, which is whatever launched the app.
    scheme = os.path.abspath(
        os.path.join(os.path.dirname(path), "colors", "wallpaper.conf")
    )
    content = f"""# {HEADER}

[Appearance]
custom_palette=true
color_scheme_path={scheme}
style=Fusion
icon_theme=Papirus-Dark
standard_dialogs=default

[Interface]
activate_item_on_single_click=1
buttonbox_layout=0
cursor_flash_time=1000
dialog_buttons_have_icons=1
gui_effects=@Invalid()
menus_have_icons=true
show_shortcuts_in_context_menus=true
toolbutton_style=4
underline_shortcut=1
wheel_scroll_lines=3
"""
    return _write(path, content)


# Markers so the Firefox user.js block can be rewritten in place without
# touching prefs the user set themselves.
FF_BEGIN = "// >>> theme_engine >>>"
FF_END = "// <<< theme_engine <<<"


def firefox(p, path):
    """Theme one Firefox profile. `path` is the profile directory.

    Unlike every other writer this one produces three files, because Firefox
    needs all three to be themed at all:

      chrome/userChrome.css   the browser UI - tabs, toolbar, menus
      chrome/userContent.css  the about: pages
      user.js                 the pref that makes Firefox read the other two

    Firefox reads all of these once, at startup. A wallpaper change repaints
    everything else live; the browser catches up the next time it is launched.
    """
    chrome = os.path.join(path, "chrome")

    # Firefox's own theming is driven by --lwt-* and a set of toolbar
    # variables. Overriding them at :root recolours the stock UI, which is far
    # less brittle than restyling individual widgets whose IDs move between
    # releases. !important because the built-in theme sets them inline.
    user_chrome = f"""/* {HEADER} */

:root {{
    --lwt-accent-color: {p['base']} !important;
    --lwt-accent-color-inactive: {p['crust']} !important;
    --lwt-text-color: {p['text']} !important;
    --lwt-selected-tab-background-color: {p['surface1']} !important;
    --lwt-tab-line-color: {p['accent']} !important;
    --lwt-toolbarbutton-icon-fill: {p['text']} !important;
    --lwt-toolbarbutton-hover-background: {p['surface1']} !important;
    --lwt-toolbarbutton-active-background: {p['surface2']} !important;
    --lwt-sidebar-background-color: {p['mantle']} !important;
    --lwt-sidebar-text-color: {p['text']} !important;

    --toolbar-bgcolor: {p['mantle']} !important;
    --toolbar-color: {p['text']} !important;
    --toolbar-field-background-color: {p['surface0']} !important;
    --toolbar-field-color: {p['text']} !important;
    --toolbar-field-focus-background-color: {p['surface1']} !important;
    --toolbar-field-focus-color: {p['text']} !important;
    --toolbar-field-border-color: {p['surface1']} !important;
    --toolbar-field-focus-border-color: {p['accent']} !important;
    --toolbarbutton-icon-fill: {p['text']} !important;
    --toolbarbutton-icon-fill-attention: {p['accent']} !important;
    --toolbarbutton-hover-background: {p['surface1']} !important;
    --toolbarbutton-active-background: {p['surface2']} !important;

    --tab-selected-bgcolor: {p['surface1']} !important;
    --tab-selected-textcolor: {p['text']} !important;
    --tab-selected-outline-color: {p['accent']} !important;
    --tabpanel-background-color: {p['base']} !important;

    --urlbar-box-bgcolor: {p['surface0']} !important;
    --urlbar-box-focus-bgcolor: {p['surface1']} !important;
    --urlbar-box-text-color: {p['text']} !important;
    --urlbar-box-hover-bgcolor: {p['surface1']} !important;

    --arrowpanel-background: {p['mantle']} !important;
    --arrowpanel-color: {p['text']} !important;
    --arrowpanel-border-color: {p['surface2']} !important;
    --panel-background: {p['mantle']} !important;
    --panel-color: {p['text']} !important;
    --panel-border-color: {p['surface2']} !important;
    --panel-item-hover-bgcolor: {p['surface1']} !important;
    --panel-item-active-bgcolor: {p['surface2']} !important;
    --panel-separator-color: {p['surface1']} !important;

    --button-bgcolor: {p['surface0']} !important;
    --button-color: {p['text']} !important;
    --button-hover-bgcolor: {p['surface1']} !important;
    --button-active-bgcolor: {p['surface2']} !important;
    --button-primary-bgcolor: {p['accent']} !important;
    --button-primary-color: {p['base']} !important;

    --focus-outline-color: {p['accent']} !important;
    --link-color: {p['blue']} !important;
    --link-color-visited: {p['magenta']} !important;
    --sidebar-background-color: {p['mantle']} !important;
    --sidebar-text-color: {p['text']} !important;
    --newtab-background-color: {p['base']} !important;
    --newtab-text-primary-color: {p['text']} !important;
    --error-text-color: {p['red']} !important;
    --warning-text-color: {p['yellow']} !important;

    scrollbar-color: {p['overlay0']} {p['mantle']} !important;
}}

#navigator-toolbox {{
    background-color: {p['base']} !important;
    border-bottom: 1px solid {p['surface1']} !important;
}}

#urlbar[focused="true"] > #urlbar-background {{
    outline-color: {p['accent']} !important;
}}

.tabbrowser-tab[selected] .tab-content {{
    border-top: 2px solid {p['accent']} !important;
}}

findbar {{
    background-color: {p['mantle']} !important;
    color: {p['text']} !important;
    border-top-color: {p['surface1']} !important;
}}

#sidebar-box, #sidebar-header {{
    background-color: {p['mantle']} !important;
    color: {p['text']} !important;
}}

menupopup, panel {{
    --panel-background: {p['mantle']} !important;
    --panel-color: {p['text']} !important;
}}

menupopup > menuitem[_moz-menuactive="true"] {{
    background-color: {p['surface1']} !important;
    color: {p['text']} !important;
}}
"""

    # about: pages only. Restyling arbitrary websites from here breaks them -
    # the sites' own dark themes are already better than anything derived from
    # a wallpaper - so this stops at Firefox's own chrome-adjacent pages.
    user_content = f"""/* {HEADER} */

@-moz-document url("about:blank"),
               url("about:newtab"),
               url("about:home"),
               url("about:privatebrowsing") {{
    :root, body {{
        background-color: {p['base']} !important;
        color: {p['text']} !important;
    }}
}}

@-moz-document url-prefix("about:") {{
    :root {{
        --in-content-page-background: {p['base']} !important;
        --in-content-page-color: {p['text']} !important;
        --in-content-box-background: {p['mantle']} !important;
        --in-content-box-background-odd: {p['surface0']} !important;
        --in-content-text-color: {p['text']} !important;
        --in-content-deemphasized-text: {p['muted']} !important;
        --in-content-border-color: {p['surface1']} !important;
        --in-content-accent-color: {p['accent']} !important;
        --in-content-primary-button-background: {p['accent']} !important;
        --in-content-primary-button-text-color: {p['base']} !important;
        --in-content-link-color: {p['blue']} !important;
        --in-content-link-color-visited: {p['magenta']} !important;
        scrollbar-color: {p['overlay0']} {p['mantle']} !important;
    }}
}}
"""

    _write(os.path.join(chrome, "userChrome.css"), user_chrome)
    _write(os.path.join(chrome, "userContent.css"), user_content)

    # user.js is Firefox's only pref-file hook and there is no drop-in
    # directory, so the block is delimited and merged rather than written
    # over the top of whatever else is in there.
    block = "\n".join([
        FF_BEGIN,
        f"// {HEADER}",
        '// userChrome.css / userContent.css are ignored without this.',
        'user_pref("toolkit.legacyUserProfileCustomizations.stylesheets", true);',
        'user_pref("browser.theme.dark-private-windows", true);',
        '// Tell pages the system is dark, so sites with a dark mode use it.',
        'user_pref("ui.systemUsesDarkTheme", 1);',
        FF_END,
        "",
    ])

    user_js = os.path.join(path, "user.js")
    existing = ""
    if os.path.exists(user_js):
        with open(user_js) as f:
            existing = f.read()
        if FF_BEGIN in existing and FF_END in existing:
            head, _, rest = existing.partition(FF_BEGIN)
            _, _, tail = rest.partition(FF_END)
            existing = head + tail.lstrip("\n")

    if existing and not existing.endswith("\n"):
        existing += "\n"
    _write(user_js, existing + block)

    return path


def xresources(p, path):
    """*.color0..15 for the X resource database.

    Anything old-school that reads xrdb - i3lock, xterm, the odd Java app -
    picks the palette up from here.
    """
    ansi = [
        "black", "red", "green", "yellow", "blue", "magenta", "cyan", "white",
        "bright_black", "bright_red", "bright_green", "bright_yellow",
        "bright_blue", "bright_magenta", "bright_cyan", "bright_white",
    ]
    lines = [f"! {HEADER}", ""]
    lines.append(f"*.background: {p['base']}")
    lines.append(f"*.foreground: {p['text']}")
    lines.append(f"*.cursorColor: {p['cursor']}")
    lines.append("")
    for i, name in enumerate(ansi):
        lines.append(f"*.color{i}: {p[name]}")
    lines.append("")
    return _write(path, "\n".join(lines))
