;; main colors
background = #1F1F1F
foreground = #FFFFFF
foreground-alt = #8F8F8F

;; shades
shade1 = #6E2C00
shade2 = #7A2E00
shade3 = #8A3100
shade4 = #A04700
shade5 = #AD4F00
shade6 = #B76300
shade7 = #C78400
shade8 = #D7A222